version: "3.8"

services:
  app:
    build:
      context: .
    container_name: pokemonapp-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./db/my-database.db:/app/db/my-database.db
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/db/my-database.db
